package flyio

import (
	"crypto/sha256"
	"encoding/hex"
	_ "embed"
	"sync"
)

// clankHostBinary is the cross-compiled linux/amd64 clank-host binary
// the provisioner pushes into a Sprite at create time. The file is
// regenerated by `make embed-host` (see Makefile) and is .gitignored;
// any developer building this package without running the Makefile
// first will see a clear `go:embed` error pointing at the missing
// path.
//
// We embed instead of downloading from a public URL on the sprite
// side so the daemon binary is fully self-contained — no external
// release infrastructure is required for self-hosters.
//
//go:embed clank-host-linux-amd64
var clankHostBinary []byte

// clankHostBinarySHA returns a hex sha256 of the embedded binary,
// computed once on demand. Used as the canonical "did this match"
// check for ensureBinaryInstalled — size collisions are rare but
// production-real (rebuild-with-no-source-change is exactly that),
// and a hash sidecar on the sprite eliminates the false-skip path.
var clankHostBinarySHA = sync.OnceValue(func() string {
	sum := sha256.Sum256(clankHostBinary)
	return hex.EncodeToString(sum[:])
})
