package flyio

import _ "embed"

// clankHostBinary is the cross-compiled linux/amd64 clank-host binary
// the provisioner pushes into a Sprite at create time. The file is
// regenerated by `make embed-host` (see Makefile) and is .gitignored;
// any developer building this package without running the Makefile
// first will see a clear `go:embed` error pointing at the missing
// path.
//
// We embed instead of downloading from a public URL on the sprite
// side so the daemon binary is fully self-contained — no external
// release infrastructure is required for self-hosters.
//
//go:embed clank-host-linux-amd64
var clankHostBinary []byte
